### ISSUE TITLE
USER STORY: Alert user actions

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/woohoo-haiku#17]
As a **user** I can **see messages displaying after taking an action** so that I **know my actions were successfully run**

## Acceptance criteria

- [x] Alert message or new view after user action

## Tasks

- [x] Add confirmation alert after user sign in, login, logout (bootstrap alerts)
- [x] Refer to new view when deleting haiku to confirm user decision
