### ISSUE TITLE
USER STORY: Browse haikus

### ISSUE THREAD

**Issue by Kay-ddggxh** [Kathrin-ddggxh/woohoo-haiku#2]
As a **Site User** I can **view a list of haikus** so that I  can **select one to read, like and comment on**

## Acceptance Criteria

- [x] Home page displays all haikus posted by users
- [x] Page navigation to minimise scrolling

## Tasks

- [x] Create list view for homepage, listing all haiku posts
- [x] Include pagination with navigation links at the bottom
